### ISSUE TITLE
Can't find oarfish executable file after cloning from the Github repository

### ISSUE THREAD

**Issue by alanlamsiu** [COMBINE-lab/oarfish#17]
Hi oarfish team,

Could ou point me to the oarfish executable file for running it? I read in https://combine-lab.github.io/oarfish/ that there should be the oarfish file but cannot find it after cloning from this repository.

Thanks.

**Comment by rob-p** [comment]
Hi @alanlamsiu,

  Cloning the repository clones the source code, it won't copy any executables.  The latest release of `oarfish` can be found on the [releases page](https://github.com/COMBINE-lab/oarfish/releases/tag/v0.4.0).

--Rob

**Comment by rob-p** [comment]
Hi @alanlamsiu,

  It looks like the HPC you are running it on has a very old version of `LIBC` which is causing this error.  We could try and create an executable using musl as the standard library.  However, one thing you might try is to see if you can build it locally yourself first (on the HPC).

install the latest rust if you don't have it yet:  

```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```  

clone the repo:

```
$ git clone https://github.com/COMBINE-lab/oarfish.git
```

build oarfish:

```
$ cd oarfish
$ cargo build --release
```

then it would live in `target/release/oarfish` if this was successful.  This might work where the above failed because it would use the version of libc that you have on the HPC, not the one present on the GitHub runner that build the current pre-compiled executables.  If that's not successful for you, let me know, and we can look into musl.

**Comment by alanlamsiu** [comment]
Thanks @rob-p for the solution. It works perfectly.

**Comment by rob-p** [comment]
You're welcome!
