### ISSUE TITLE
Clarification on "supplementary alignment" in logs

### ISSUE THREAD

**Issue by iza-mcac** [COMBINE-lab/oarfish#37]
Hello Oarfish team,

I am analyzing the logs generated by Oarfish and noticed a read subgroup named as `supplementary alignment`. Here is an excerpt from the log:
╭─────────────────────────────────
│ reason                          │ count  │
├─────────────────────────────────
│ too far from 5' end             │ 0      │
│ too far from 3' end             │ 0      │
│ score too low                   │ 79     │
│ aligned fraction too low        │ 0      │
│ aligned length too short        │ 0      │
│ inconsistent orientation        │ 0      │
│ supplementary alignment         │ 34564  │
│ reads with valid best alignment │ 794444 │
╰─────────────────────────────────
I could not find detailed information about the term `supplementary alignment` in the README or the preprint. Could you clarify:
1. What exactly is meant by "supplementary alignment" in this context?
2. Under what circumstances would a read be categorized this way and if it is included or excluded in the analysis.

Thank you for your time and for developing such a great tool!

Best regards,

**Comment by rob-p** [comment]
Hi @iza-mcac,

  So in our context, this simply means that `minimap2` has marked these alignments as "Supplementary".  This, unfortunately, is a SAM flag that doesn't have a widely accepted definition.  However, in the context of `minimap2`, I believe it generally means that the alignment [was either chimeric](https://github.com/lh3/minimap2/issues/122) or had very large linear gaps that don't match potential intron boundaries (irrelevant in the context of `oarfish` since we're aligning to the transcriptome anyway rather than the genome).

Best,
Rob

**Comment by iza-mcac** [comment]
Hey @rob-p 
Thanks for the very-fast in-depth explanation!

**Comment by rob-p** [comment]
My pleasure :).
